server:
  port: 9091

spring:
  application:
    name: AuctionService

  datasource:
    url: jdbc:mysql://localhost:3306/bfsi_staging?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 55555555
    driver-class-name: com.mysql.cj.jdbc.Driver  #  Explicitly define driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # ✅ Formats SQL output for readability

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always  #  Shows full health details
  health:
    defaults:
      enabled: true
    db:
      enabled: true  # Enables DB health check

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9095/eureka